### PR TITLE
Rohit

### PR DESCRIPTION
**Pull request by rarora4**

### CODE REVIEW

**Comment by rarora4** [comment]
@bhashwanth: Improved Folder structure as you had request.
@yatish27 Review Sample File for the Simple Parser.

**Comment by yatish27** [comment]
@rarora4 I had few changes 
1. Can we have corresponding issue for this PR.
2 .Can we convert the .txt file to .md file
3. Can we also make .js file for simple parser. I know it is not the final product but still

**Comment by kumar-utsav** [comment]
@yatish27  I will do all that tonight.

**Comment by rarora4** [comment]
1. There is already issue #37 corresponding to it.
2. This is a sample file that should be entered into the textbox. Therefore it is ".txt" to see how output would look.
3. @kumar-utsav it taking care of that.

**Comment by yatish27** [comment]
@kumar-utsav Once you make those changes, merge it in master

**Comment by rarora4** [comment]
#41 will take care of that.

**Comment by yatish27** [comment]
Add Labels to corresponding issues not PR

**Comment by yatish27** [comment]
Which issue does this refer ?

**Comment by yatish27** [comment]
Add the Issue No as the name for PR like "Fixes #xy" and not the branch/user name

**Pull request merged**
