### PR TITLE
Fixes #12: Basic working MVP in Ruby track

### LINKED ISSUE #12: Code for medium/complex markdowns in Ruby

### PR DESCRIPTION
**Pull request by yatish27**

### CODE REVIEW

**Comment by yatish27** [comment]
Fixes #12

**Comment by yatish27** [comment]
@kumar-utsav Can you review and change labels?

**Comment by kumar-utsav** [comment]
@yatish27  please mention the issue it refers to. Also, change the name of the PR based on the format we have been using,

**Comment by yatish27** [comment]
@kumar-utsav Done. Do change the labels after you provide the review.
Add label and merge if alls good

**Pull request merged**
