### PR TITLE
Fixes #13, fixes #14, fixes #19: Added unit test cases for simple, medium and complex parsers

### LINKED ISSUE #13: Create Test cases for simple prototypes and improve existing designs

### LINKED ISSUE #14: Create Tests for Medium complex design and improve existing design

### LINKED ISSUE #19: Create Tests for Very complex design and improve existing design

### PR DESCRIPTION
**Pull request by bhashwanth**
@rarora4 added unit test cases for the parsers. Review and merge. You can see the output by running SpecRunner.html

### CODE REVIEW

**Comment by bhashwanth** [comment]
#fixes 13, 14, 21

**Comment by yatish27** [comment]
@bhashwanth tag each issue. Also please name the PR properly

**Comment by yatish27** [comment]
@bhashwanth Why is the entire jasmine library in here. Please remove that
ADD THE TESTCASES FOR THE NPM PACKAGE. Remove the tests for Complex parser and add it in the npm package folder

**Comment by bhashwanth** [comment]
@yatish27 Removed the jasmine standalone version and added the node version. Put complex test cases in mark_parser. Review and Merge.

**Comment by rarora4** [comment]
@Seems perfect. Bash you can be future Jasmine Programmer as well. Go for it dude!

**Pull request merged**
