### PR TITLE
Fixes #25:Add Medium Complex Parsing Capabilities

### LINKED ISSUE #25: Code for medium complex markdowns in JavaScript

### PR DESCRIPTION
**Pull request by rarora4**
@yatish27 @bhashwanth Please review initial working model for the medium complex parsers.

### CODE REVIEW

**Comment by yatish27** [comment]
@rarora4 Which issue does this work on ?
Check my previous comments lets work that way

**Comment by rarora4** [comment]
#25

**Comment by yatish27** [comment]
@rarora4 Lets make a convention to make name of the PR as "Fixes #x, #y"

**Comment by rarora4** [comment]
@yatish27 @bhashwanth Please review the current code.
Contains #18

**Comment by yatish27** [comment]
Looks good

**Pull request merged**
